export const LOGOUT = 'LOGOUT';

export const FETCHAPI_USER_CREATE = 'FETCHAPI_USER_CREATE';
export const FETCHAPI_USER_INFO = 'FETCHAPI_USER_INFO';
export const FETCHAPI_USER_LIST = 'FETCHAPI_USER_LIST';
export const FETCHAPI_USER_LOGIN = 'FETCHAPI_USER_LOGIN';
export const FETCHAPI_TRANSACTION_LIST = 'FETCHAPI_TRANSACTION_LIST';
export const FETCHAPI_TRANSACTION_CREATE = 'FETCHAPI_TRANSACTION_CREATE';

export const USER_ERROR_API = 'USER_ERROR_API';
export const TRANSACTION_ERROR_API = 'TRANSACTION_ERROR_API';

export const RECEIVEAPI_USER_CREATE = 'RECEIVEAPI_USER_CREATE';
export const RECEIVEAPI_USER_INFO = 'RECEIVEAPI_USER_INFO';
export const RECEIVEAPI_USER_LIST = 'RECEIVEAPI_USER_LIST';
export const RECEIVEAPI_USER_LOGIN = 'RECEIVEAPI_USER_LOGIN';
export const RECEIVEAPI_TRANSACTION_LIST = 'RECEIVEAPI_TRANSACTION_LIST';
export const RECEIVEAPI_TRANSACTION_CREATE = 'RECEIVEAPI_TRANSACTION_CREATE';
